services:
  # Backend API
  - type: web
    name: giki-chatbot
    runtime: python
    region: oregon  # Free tier region
    plan: free
    branch: main
    buildCommand: |
      cd src
      pip install -r ../requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: cd src && gunicorn --bind 0.0.0.0:$PORT --timeout 600 --workers 2 backend:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_HOST
        sync: false
      - key: LLM_PROVIDER
        value: groq
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: admin123
      - key: GIKI_LATITUDE
        value: "33.9407"
      - key: GIKI_LONGITUDE
        value: "72.6267"
      - key: WEATHER_API_KEY
        sync: false
      - key: EXCHANGE_RATE_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
