name: Build and deploy Python app to Azure Web App - giki-chatbot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # 1. Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install dependencies (only to verify, not to deploy)
      - name: Install dependencies for verification
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      # 4. Login to Azure (uses OIDC with secrets you already set up)
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_38133CBEC43D4DB08349318836B84668 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4233E1EE5A4E4F9D9F299BCACFA84245 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B79820CEDAC0430E85A7E7840E09FA7C }}

      # 5. Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'giki-chatbot'
          slot-name: 'Production'
          package: .
